---
- name: Install certbot and the cloudflare plugin
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python3-certbot-dns-cloudflare

- name: Create a directory for keeping the configuration files
  file:
    path: /etc/certbot_plugin_configs
    mode: "0600"
    owner: root
    group: root
    state: directory

- name: Deploy cloudflare credentials
  template:
    src: cloudflare.ini
    dest: /etc/certbot_plugin_configs/cloudflare.ini
    mode: "0600"
    owner: root
    group: root
  no_log: True

- name: Get certificates
  command: "certbot certonly \
    --dns-cloudflare \
    --dns-cloudflare-credentials /etc/certbot_plugin_configs/cloudflare.ini \
    -d {{ item.domain }} --non-interactive --agree-tos -m {{ item.expiry_notification_email }} "
  with_items: "{{ certbot_domains }}"
  args:
    creates: /etc/letsencrypt/live/"{{ item }}"

- name: Create a file containing all of the domains 
  template:
    src: certbot_domains
    dest: /etc/certbot_domains
    mode: "0750"
    owner: root
    group: root

- name: Deploy the script to create fullchains and reload HAProxy
  copy:
    src: create_fullchains.sh 
    dest: /etc/cron.weekly/create_fullchains.sh
    owner: root
    group: root
    mode: "0550"

- name: Create a directory to keep the fullchains which HAProxy requires
  file:
    path: "/etc/ssl/{{ item.domain }}"
    mode: "0770"
    owner: haproxy
    group: root
    state: directory
  with_items: "{{ certbot_domains }}"
