---

- name: create /storage/grafana
  file:
    path: /storage/grafana
    state: directory
    owner: 472

- name: deploy the grafana container
  docker_container:
    image: grafana/grafana-enterprise:9.0.3
    name: grafana
    network_mode: main
    networks:
      - name: main
    container_default_behavior: compatibility
    restart_policy: always
    volumes:
      - /storage/grafana:/var/lib/grafana
# ref: https://grafana.com/docs/grafana/next/setup-grafana/configure-grafana/#configure-with-environment-variables
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
    ports:
      - "3000:3000"
      
