- hosts:
    - all
  remote_user: opc
  become: yes
  roles:
    - rhel_common
  
- hosts:
    - tag_name=pyrokar
  remote_user: opc
  become: yes
  roles:
    - haproxy
  vars:
    haproxy_conf: pyrokar_haproxy.cfg
