---
- hosts:
    - hcloud
  remote_user: root
  roles:
    - geerlingguy.docker
    - rhel_common
    - role: consul
      tags: role_consul
  vars:
    consul_subnet: 172.21.0.0/16
    consul_retry_join: 172.21.0.10

- hosts:
    - xardas
  remote_user: root
  roles:
    - lvm
    - fstab
    - prometheus
    - role: grafana
      tags: role_grafana
  vars:
    grafana_ini_filename: grafana.ini.xardas_dev

