---
- hosts:
    - hcloud
  remote_user: root
  roles:
    - rhel_common
    - geerlingguy.docker
    - role: consul
      tags: role_consul
  vars:
    consul_subnet: 172.21.0.0/16
    consul_retry_join: 172.21.0.10

- hosts:
    - hcloud
  remote_user: root
  roles:
    #- grafana
    - prometheus
  vars:
    grafana_ini_filename: grafana.ini.xardas_dev

