# docker_swarm dependency
- name: Install the python module for docker
  pip:
    name: docker
    state: present

- name: Init a new swarm with default parameters
  docker_swarm:
    state: present
    advertise_addr: 10.0.0.10
  when: swarm_manager

- name: Register the deploy token
  command: "/usr/bin/docker swarm join-token worker -q"
  register: join_token
  when: swarm_manager

- name: Join the swarm
  docker_swarm:
    state: join
    remote_addrs: [ '10.0.0.10:2377' ]
    join_token: "{{ hostvars['xardas']['join_token']['stdout'] }}"
  when: not swarm_manager
 
