- name: Enable EPEL
  dnf:
    name: epel-release
    state: present

- name: Install fail2ban
  dnf:
    name: fail2ban
    state: present

- name: Enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
