---
- name: Create a main network
  community.docker.docker_network:
    name: main

# configuration reference:
# https://github.com/prometheus/node_exporter
- name: deploy the node exporter
  docker_container:
    image: prom/node-exporter:v1.3.1
    name: node-exporter
    container_default_behavior: compatibility
    restart_policy: always
    command: "--path.rootfs=/host"
    network_mode: host
    pid_mode: host
    volumes:
      - '/:/host:ro,rslave'

- name: deploy cadvisor
  docker_container:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    name: cadvisor
    network_mode: main
    networks:
      - name: main
    container_default_behavior: compatibility
    restart_policy: always
    ports:
      - "8080:8080"

