---
- name: deploy the node exporter
  docker_container:
    image: prom/node-exporter:v1.3.1
    name: node-exporter
    container_default_behavior: compatibility
    restart_policy: always
    ports:
      - "9100:9100"

- name: deploy cadvisor
  docker_container:
    image: gcr.io/cadvisor/cadvisor:v0.39.3
    name: cadvisor
    container_default_behavior: compatibility
    restart_policy: always
    ports:
      - "8080:8080"

