- name: Check if we're using Oracle Linux
  stat:
    path: /etc/oracle-release
  register: oracle_release

- name: Enable EPEL
  dnf:
    name: epel-release
    state: present
  when: not oracle_release.stat.exists

- name: Enable the Oracle EPEL repo
  yum_repository:
    name: ol8_developer_EPEL
    description: Oracle's EPEL repository
    baseurl: https://yum$ociregion.$ocidomain/repo/OracleLinux/OL8/developer/EPEL/$basearch/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
    gpgcheck: yes
    enabled: yes
  when: oracle_release.stat.exists

- name: Install fail2ban
  dnf:
    name: fail2ban
    state: present

- name: Deploy the fail2ban config
  copy:
    src: fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 750
  notify: Restart fail2ban

- name: Enable fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes


